# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LearnTextVis
email: test@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Introduction to Text Analysis and Text Visualization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://learntextvis.github.io" # the base hostname & protocol for your site
twitter_username: learntextvis
github_username:  learntextvis
facebook_username: learntextvis
permalink: /:title/

# Build settings
encoding: utf-8
markdown: kramdown
redcarpet:
  extensions:
    - "no_intra_emphasis"
    - "tables"
    - "fenced_code_blocks"
    - "autolink"
    - "strikethrough"
    - "superscript"
    - "highlight"
    - "footnotes"
