# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Seattle Maps
email: vlandham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Historical Maps of Seattle and Surrounding areas.
baseurl: "/seattle_maps" # the subpath of your site, e.g. /blog
baseurlslash: "/seattle_maps/img/" # the subpath of your site, e.g. /blog
baseurlthumb: "/seattle_maps/img/thumb/"
url: "http://vallandingham.me" # the base hostname & protocol for your site
permalink: /:title/

collections:
  maps:
    output: true

# Build settings
encoding: utf-8
markdown: kramdown
redcarpet:
  extensions:
    - "no_intra_emphasis"
    - "tables"
    - "fenced_code_blocks"
    - "autolink"
    - "strikethrough"
    - "superscript"
    - "highlight"
    - "footnotes"
